#load libraries
library(dplyr)
library(tidyr)
library(ggplot2)
library(RColorBrewer)
library(tibble)
library(arules)
library(arulesViz)
library(caret)
library(readr)
library(pdftools)
library(stringr)
library(gridExtra)
library(kableExtra)

library(treemap)
